### ISSUE TITLE
Sky flashing

### ISSUE THREAD

**Issue by Twinkletoe** [ChildrenOfUr/coUclient#101] opened 2014-07-28 20:00 UTC
I am in Chrome. When I move around in Jantik Jog, the sky flashes back and forth between blue and white.

**Comment by Klikini** [comment] 2015-04-02 01:59
Can anyone confirm that this is still an issue?

@Twinkletoe @sibilantsibyl @bribling

**Comment by RobertMcDermot** [comment] 2015-04-08 23:15
I am not able to reproduce this issue and without a current response that says it's still happening, I'm going to close this bug. If it is still happening, feel free to open a new bug with details.

**Closed by RobertMcDermot** 2015-04-08 23:15 UTC
Labels: bug, Pending Response
