### ISSUE TITLE
Flying Pigs

### ISSUE THREAD

**Issue by jellybino** [ChildrenOfUr/coUclient#172] opened 2014-12-12 22:31 UTC
This was taken in Groddle Forest - Thicket:

![flying pig](https://cloud.githubusercontent.com/assets/8164843/5420543/a8b0d95e-8224-11e4-94c2-c6ee99d49679.png)

**Comment by ppvk** [comment] 2015-01-10 02:37
This is a duplicate of #124

**Closed by ppvk** 2015-01-10 02:37 UTC
