### ISSUE TITLE
Browser Issue

### ISSUE THREAD

**Issue by PickleChip** [ChildrenOfUr/coUclient#198] opened 2015-06-23 13:21 UTC
Does't work properly on chrome and oprea browsers.

**Comment by RobertMcDermot** [comment] 2015-06-23 13:32
Can you provide any more information on what part isn't working, i.e. what does it do/not do and what do you think that it should do?

If you have a screenshot, that could be helpful as well.

**Comment by Catatafishs** [comment] 2015-06-27 21:21
I've noticed that it does not seem to work properly on Firefox and Chrome as well.

The login song continues to play when the world is loaded and my Glitchen doesn't seem to load.

This is what it looks like for me: https://i.gyazo.com/cece978c2d54b3b89184f0cb52349d6b.png

**Comment by RobertMcDermot** [comment] 2015-06-28 23:25
@Catatafishs Thanks for the screenshot. This is not necessarily a problem with any browser. This is (unfortunately) somewhat common for us at the moment. What's happening here is that the server is not responding and a couple of things are waiting on it to start up the main game loop. This results in the broken image you've posted here.

If this happens to you, we're sorry. We do try to keep an eye on the server health and restart it if need be. Try coming back later in the day or the next day and things will hopefully be better. 

Closing this as it is not a bug in the client but rather an intermittent issue with the server.

**Closed by RobertMcDermot** 2015-06-28 23:25 UTC
Labels: Pending Response
